import STL from "./stl";
import TCSC from "./tcsc";
import array from "./array";
import string from "./string";
import Math from "./math";
import TWO_D_ARRAY from "./2darray";
import RECURSION from "./recursion";
import STACK_QUEUE from "./stack&queue";
import LINKED_LIST from "./linkedlist";
import TREE from "./tree";
import GRAPH from "./graph";
import STAR_PATTERN from "./starpattern";
import FUNCTION from "./function";
import IFELSE from "./ifelse";
import FOR_LOOP from "./forloop";
import WHILE_LOOP from "./whileloop";
import LOGICAL_QUESTIONS from "./logicalquestions";
const topics = [STL, TCSC, array, string, Math, TWO_D_ARRAY, RECURSION,  STACK_QUEUE, LINKED_LIST, TREE, GRAPH, STAR_PATTERN, FUNCTION, IFELSE, FOR_LOOP, LOGICAL_QUESTIONS];

export default topics;